routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/  

Route::get("admin", "HomeController@dashboard")->name('dashboard');
Route::resource('admin/roles', 'RoleController');
Route::resource("admin/users", "UserController");
Route::resource('admin/categories', 'CategoryController');
Route::resource('admin/products', 'ProductController');
Route::resource('admin/testimonies', 'TestimonyController');
Route::resource('admin/orders', 'OrderController');

Route::get('{path}', function () {
    return view('index');
})->where('path', '(.*)');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;
class ProductController extends Controller
{
    public function __construct()
    {
        // $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = \App\Product::get();
        return view('admin.products.index', ['products' => $products]);
    }
    public function filterCondition(Request $request){
        
        $products = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->where('products.product_condition', $request->product_condition )->get();
        return $products;
    }
    public function searchCategory(Request $request){
        $products = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->where('products.product_category', $request->id )->get();
        return $products;
    }

    public function all()
    {
        $products = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->get();
        return $products;
    }
    public function allPaginate()
    {
        $products = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->inRandomOrder()->limit(8)->get();
        return $products;
    }
    public function search(Request $request)
    {
        $products = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->where('product_name' , 'like' , '%'. $request->search .'%')->get();
        return $products;
    }

    public function data($id){
        $product = \App\Product::leftJoin('categories', "categories.id", "products.product_category")->select('products.*', 'categories.category_name')->where('products.id', $id)->first();
        return $product;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = \App\Category::get();

        return view("admin.products.create", $data); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_product = new \App\Product;
        $new_product->product_category = $request->product_category;
        $new_product->product_condition = $request->product_condition;
        $new_product->product_name = $request->product_name;
        $new_product->product_description = $request->product_description;
        $new_product->product_price = $request->product_price;
        $new_product->product_stock = $request->product_stock;
        $images = [];
        if($request->hasFile('files')){
            foreach ($request->file('files') as $key) {
                
                $fileName = Str::random(8) . '.' . $key->getClientOriginalExtension();
                $move = $key->move('uploads/product_images', $fileName);
                array_push($images, $fileName);
            }
            $image = implode(',' , $images);
            $new_product->product_image = $image;
        }else{
            return 'ga ada';
        }
            

        $new_product->save();
        return $request->file('file');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['product'] = \App\Product::findOrFail($id);
        $data['categories'] = \App\Category::get();

        return view('admin.products.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $images = [];
        $product = \App\Product::findOrFail($id);

        $product->product_category = $request->get('product_category');
        $product->product_condition = $request->product_condition;
        $product->product_name = $request->get('product_name');
        $product->product_description = $request->get('product_description');
        $product->product_stock = $request->get('product_stock');
        $product->product_price = $request->get('product_price');
        if($request->file('product_image')){
            // dd($request->all());    
            foreach ($request->file('product_image') as $key) {
                // dd($key->extension());
                $fileName = Str::random(8) . '.' . $key->getClientOriginalExtension();
                $move = $key->move('uploads/product_images', $fileName);
                array_push($images, $fileName);
            }
            $image = implode(',' , $images);
            $product->product_image = $image;
        }

        $product->save();

        return redirect()->route('products.index')->with('status', 'Product successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function delete($id)
    {
        $product = \App\Product::findOrFail($id);
        // File::delete('uploads/product_images/' . $product->product_images);
        $product->delete();
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Create Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Product</a></li>
                    <li class="breadcrumb-item">Create Product</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Elements -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Please fill out this field</h3>
        </div>
        <div class="block-content">
            <div class="row push">
                <div class="col-lg-12">

                    <label for="product_categories">Product Category</label><br>
                    <select class="form-control"  v-model="product_category">
                        <option value="0">Pilih Kategori ...</option>
                        @foreach ($categories as $item)
                        <option value="{{$item->id}}">{{$item->category_name}}</option>
                        @endforeach
                    </select>
                    <br>
                    
                    <label for="product_categories">Product Category</label><br>
                    <select class="form-control"  v-model="product_condition">
                        <option value="0">Pilih Kondisi ...</option>
                        <option value="Second Kualitas Terbaik">Second Kualitas Terbaik</option>
                        <option value="Second Populer">Second Populer</option>
                        <option value="Second Dibawah 1 juta">Second Dibawah 1 juta</option>
                    </select>
                    
                    <br>

                    <label for="product_name">Product Name</label> <br>
                    <input type="text" class="form-control" value="" v-model="product_name" >
                    <br>

                    <label for="product_image">Product Image</label>
                    <input type="file" ref="file" class="form-control" multiple @change="onChangeFileUpload()" name="file">
                    <br>

                    <label for="product_description">Product Description</label><br>
                    <textarea name="" class="form-control" v-model="product_description"></textarea>
                    <br>


                    <label for="product_stock">Engineering Test</label><br>
                    <input type="number" class="form-control" min="0" max="10" value="" v-model="product_stock" >
                    <br>

                    <label for="product_price">Product Price</label> <br>
                    <input type="number" class="form-control" value="" v-model="product_price" >
                    <br>

                    <button @click="product_store" class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<script>
    var App = new Vue({
    el: '#app',
        data() {
        return {
            uri: 'http://127.0.0.1:8000/',
            categories : {},
            product_name: '',
            file: [], //UNTUK MENYIMPAN DATA FILE YANG AKAN DIUPLOAD
            product_description: '',
            product_category: 0,  
            product_condition: 0,  
            product_stock: '',
            product_price: '',
            products: {},
        }
    },
    mounted() {
        // this.categories_all();
    },
    methods: {
        onChangeFileUpload() {
            this.file = this.$refs.file.files;
            console.log(this.file.length)
        },
        product_store() {
            let formData = new FormData();
            formData.append('product_category', this.product_category);
            formData.append('product_condition', this.product_condition);
            formData.append('product_name', this.product_name);
            
            for( var i = 0; i < this.file.length; i++ ){
                let file = this.file[i];
                console.log(file);
                formData.append('files[' + i + ']', file);
            }
            formData.append('product_description', this.product_description);
            formData.append('product_stock', this.product_stock);
            formData.append('product_price',  this.product_price);
            axios.post(this.uri + 'api/products/store',
                formData, {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                }
            ).then(res => {
                console.log(res),
                this.file = [],
                this.product_category = 0,
                this.product_category = 0,
                this.product_name ="",
                this.product_description = '',
                this.product_stock = '',
                this.product_price = '',
                Swal.fire(
                    'Good job!',
                    'You clicked the button!',
                    'success'
                )
            })
            .catch(err => alert(err.response.data.message));
        },
        categories_all() {
            axios.get(this.uri + 'api/categories/all').then(response => {
            this.categories = response.data
            }).catch(error => {
            console.log(error)
            })
        },

    }
    })

</script>

@endsection

resources/views/admin/products/edit.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Edit Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Product</a></li>
                    <li class="breadcrumb-item">Edit Product</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Elements -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Please fill out this field</h3>
        </div>
        <div class="block-content">
            <form action="{{route('products.update', ['product'=>$product->id])}}" method="POST"
                enctype="multipart/form-data">
                @csrf
                <input type="hidden" value="PUT" name="_method">
                <!-- Basic Elements -->

                <div class="row push">
                    <div class="col-lg-12">

                        <label for="categories">Categories</label>
                        <select class="form-control" name="product_category">
                            @foreach ($categories as $item)
                            <option @if($product->product_category == $item->id) selected @endif
                                value="{{ $item->id }}">{{ $item->category_name }}</option>
                            @endforeach
                        </select>
                        <br>
                        <label for="product_categories">Product Category</label><br>
                        <select class="form-control"  v-model="product_condition">
                            <option value="0">Pilih Kondisi ...</option>
                            <option value="Second Kualitas Terbaik">Second Kualitas Terbaik</option>
                            <option value="Second Populer">Second Populer</option>
                            <option value="Second Dibawah 1 juta">Second Dibawah 1 juta</option>
                        </select>
                        <br>

                        <label for="title">Product Name</label><br>
                        <input type="text" class="form-control" value="{{$product->product_name}}" name="product_name"
                            placeholder="Product Name" />
                        <br>

                        <label for="product_image">Product Image</label><br>
                        <small class="text-muted">Current cover</small><br>
                        @if($product->product_image)
                        @php
                            $image = explode(',',$product->product_image);   
                            // var_dump($image);
                        @endphp
                        @foreach ($image as $item)
                            <img src="{{asset('uploads/product_images/' . $item)}}" width="96px" />
                        @endforeach
                        @endif
                        <br><br>
                        <input type="file" class="form-control" name="product_image[]" multiple>
                        <small class="text-muted">Kosongkan jika tidak ingin mengubah cover</small>
                        <br><br>

                        <label for="product_description">Product Description</label> <br>
                        <textarea name="product_description" id="product_description"
                            class="form-control">{{$product->product_description}}</textarea>
                        <br>

                        <label for="product_stock">Engineering Test</label><br>
                        <input type="number" min="0" max="10" class="form-control" placeholder="product_stock" id="product_stock"
                            name="product_stock" value="{{$product->product_stock}}">
                        <br>

                        <label for="product_price">Product Price</label><br>
                        <input type="text" class="form-control" name="product_price" placeholder="product_price"
                            id="product_price" value="{{$product->product_price}}">
                        <br>

                        <button class="btn btn-primary" value="submit">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/products/index.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Data Products</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item">Products</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Dynamic Table Full -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Dynamic Table <small>Full</small></h3>
            <div class="d-flex">
                <input type="text" v-model="search" class="form-control" placeholder="search Something" @keydown="searchProduct()">
                <div class="input-group">
                    <div class="input-group-btn">
                        <a href="{{route('products.create')}}" class="btn btn-success"><i
                                class="fas fa-plus-circle"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="block-content block-content-full">

            <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _es6/pages/be_tables_datatables.js -->
            <div style="overflow-x: scroll">
                
            <table class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 80px;">#</th>
                        <th><b>Product Image</b></th>
                        <th><b>Product Categories</b></th>
                        <th><b>Product Name</b></th>
                        <th><b>Product Description</b></th>
                        <th><b>Product Stock</b></th>
                        <th><b>Product Price</b></th>
                        <th><b>Action</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="product in products">
                        <td class="text-center">@{{ product.id }}</td>
                        <td class="d-none d-sm-table-cell">
                            <img v-if="product.product_image" width="80"
                                :src="uri + 'uploads/product_images/'+ convert(product.product_image)" alt="">
                            <div v-else>Not set</div>
                        </td>
                        <td class="d-none d-sm-table-cell">@{{ product.category_name }}</td>
                        <td class="d-none d-sm-table-cell">@{{ product.product_name }}</td>
                        <td class="d-none d-sm-table-cell">@{{ product.product_description }}</td>
                        <td class="d-none d-sm-table-cell">@{{ product.product_stock }}</td>
                        <td class="d-none d-sm-table-cell">@{{ product.product_price }}</td>
                        <td class="d-none d-sm-table-cell">
                            <a class="btn btn-info text-white btn-sm"
                                :href="uri + 'admin/products/' + product.id + '/edit'">Edit</a>
                            <a href="#" @click="product_delete(product.id)" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- END Dynamic Table Full -->
</div>

@endsection

@section('script')

<script>
    var App = new Vue({
        el : '#app',
        data(){
            return{
                uri : 'http://127.0.0.1:8000/',
                products : {},
                search : null,
            }
        },
        mounted() {
            this.products_all();
        },
        methods : {
            searchProduct(){
                if(this.search){
                    axios.post(this.uri + 'api/products/search', {
                        search : this.search
                    }).then(response => {
                        this.products = response.data
                        console.log(response.data)
                    }).catch(error => {
                        console.log(error)
                    })
                }else{
                    this.products_all()
                }
            },
            products_all(){
                axios.get(this.uri + 'api/products/all').then(response => {
                    this.products = response.data
                    console.log(response.data)
                }).catch(error => {
                    console.log(error)
                })
            },
            convert(img){
                var image = img.split(',')
                console.log(image)
                return image[0] 
            },
            product_delete(id){
                Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        axios.delete(this.uri + 'api/products/delete/' + id).then(response => {
                            this.products_all();
                            Swal.fire(
                                'Good job!',
                                'You clicked the button!',
                                'success'
                            )
                        }).catch(error => console.log(error))
                        
                    }
                })
            }
        }
    })
</script>

@endsection