routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/  

Route::get("admin", "HomeController@dashboard")->name('dashboard');
Route::resource('admin/roles', 'RoleController');
Route::resource("admin/users", "UserController");
Route::resource('admin/categories', 'CategoryController');
Route::resource('admin/products', 'ProductController');
Route::resource('admin/testimonies', 'TestimonyController');
Route::resource('admin/orders', 'OrderController');

Route::get('{path}', function () {
    return view('index');
})->where('path', '(.*)');

app/Testimony.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Testimony extends Model
{
    //
}

app/Http/Controllers/TestimonyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Testimony;
use Illuminate\Support\Str;
class TestimonyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $testimony = \App\Testimony::get();
        return view('admin.testimonies.index', ['testimonies' => $testimony]);
    }
    public function all()
    {
        $testimony = \App\Testimony::leftJoin('products', "testimonies.product_id", "products.id")->select('products.product_name', 'testimonies.*')->get();
        return $testimony;
    }
    public function allPublish()
    {
        $testimony = \App\Testimony::leftJoin('products', "testimonies.product_id", "products.id")->select('products.product_name', 'testimonies.*')->where('is_publish' , true)->get();
        return $testimony;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['products'] = \App\Product::all();

        return view("admin.testimonies.create", $data); 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $testimony = new \App\Testimony();
        $testimony->product_id = $request->product_id;
        $testimony->name = $request->name;
        $testimony->is_publish = $request->is_publish;
        $testimony->testimony = $request->testimony;
        $images = [];
        if($request->hasFile('files')){
            foreach ($request->file('files') as $key) {
                
                $fileName = Str::random(8) . '.' . $key->getClientOriginalExtension();
                $move = $key->move('uploads/testimony_images', $fileName);
                array_push($images, $fileName);
            }
            $image = implode(',' , $images);
            $testimony->image = $image;
        }else{
            return 'ga ada';
        }
            

        $testimony->save();
        return $request->file('file');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['testimony'] = \App\Testimony::findOrFail($id);
        $data['products'] = \App\Product::get();

        return view('admin.testimonies.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $images = [];
        $testimony = \App\Testimony::findOrFail($id);

        $testimony->product_id = $request->get('product_id');
        $testimony->name = $request->name;
        $testimony->testimony = $request->get('testimony');
        $testimony->is_publish = $request->get('is_publish');
        if($request->file('image')){
            // dd($request->all());    
            foreach ($request->file('image') as $key) {
                // dd($key->extension());
                $fileName = Str::random(8) . '.' . $key->getClientOriginalExtension();
                $move = $key->move('uploads/testimony_images', $fileName);
                array_push($images, $fileName);
            }
            $image = implode(',' , $images);
            $testimony->image = $image;
        }

        $testimony->save();

        return redirect()->route('testimonies.index')->with('status', 'Product successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function delete($id)
    {
        $testimony = \App\Testimony::findOrFail($id);
        // File::delete('uploads/testimony_images/' . $testimony->product_images);
        $testimony->delete();
    }
}

resources/views/admin/testimonies/create.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Create Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Product</a></li>
                    <li class="breadcrumb-item">Create Product</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Elements -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Please fill out this field</h3>
        </div>
        <div class="block-content">
            <div class="row push">
                <div class="col-lg-12">

                    <label for="product_categories">Product</label><br>
                    <select class="form-control"  v-model="product_id">
                        <option value="0">Pilih Kategori ...</option>
                        @foreach ($products as $item)
                            <option value="{{$item->id}}" >{{$item->product_name}}</option>
                        @endforeach
                    </select>
                    <br>
                    <label for="product_name">Name</label> <br>
                    <input type="text" class="form-control" value="" placeholder="customer name" v-model="name" >
                    <br>

                    <label for="product_image">Product Image</label>
                    <input type="file" ref="file" class="form-control" multiple @change="onChangeFileUpload()" name="file">
                    <br>

                    <label for="product_description">Testimony</label><br>
                    <textarea name="" class="form-control" placeholder="Write a testimony" v-model="testimony"></textarea>
                    <br>

                    <select class="form-control"  v-model="is_publish">
                        <option value="0">Publish Later</option>
                        <option value="1">Publish Immadiately</option>
                    </select>
                    <br>
                    <button @click="testimony_store" class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<script>
    var App = new Vue({
    el: '#app',
        data() {
        return {
            uri: 'http://127.0.0.1:8000/',
            file: [], //UNTUK MENYIMPAN DATA FILE YANG AKAN DIUPLOAD
            product_id: '',
            is_publish: 0,
            testimony: '',
            name: '',
            products : [],
        }
    },
    mounted() {
        this.products_all()
    },
    methods: {
        onChangeFileUpload() {
            this.file = this.$refs.file.files;
            console.log(this.file.length)
        },
        testimony_store() {
            let formData = new FormData();
            formData.append('product_id', this.product_id);
            formData.append('name', this.name);
            formData.append('testimony', this.testimony);
            for( var i = 0; i < this.file.length; i++ ){
                let file = this.file[i];
                console.log(file);
                formData.append('files[' + i + ']', file);
            }
            formData.append('is_publish', this.is_publish);
            axios.post(this.uri + 'api/testimonies/store',
                formData, {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                }
            ).then(res => {
                console.log(res),
                this.file = [],
                this.product_id = 0,
                this.is_publish = 0,
                this.file =[],
                this.testimony = '',
                this.name = '',
                Swal.fire(
                    'Good job!',
                    'You clicked the button!',
                    'success'
                )
            })
            .catch(err => alert(err.response.data.message));
        },
        products_all(){
                axios.get(this.uri + 'api/products/all').then(response => {
                    this.products = response.data
                    console.log(response.data)
                }).catch(error => {
                    console.log(error)
                })
            },

        }
    })

</script>

@endsection

resources/views/admin/testimonies/edit.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Edit Product</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="#">Product</a></li>
                    <li class="breadcrumb-item">Edit Product</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Elements -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Please fill out this field</h3>
        </div>
        <div class="block-content">
            <form action="{{route('testimonies.update', ['testimony'=>$testimony->id])}}" method="POST"
                enctype="multipart/form-data">
                @csrf
                <input type="hidden" value="PUT" name="_method">
                <!-- Basic Elements -->

                <div class="row push">
                    <div class="col-lg-12">

                        <label for="categories">Product</label>
                        <select class="form-control" name="product_id">
                            @foreach ($products as $item)
                            <option @if($testimony->product_id == $item->id) selected @endif
                                value="{{ $item->id }}">{{ $item->product_name }}</option>
                            @endforeach
                        </select>
                        <br>

                        <label for="title">Customer Name</label><br>
                        <input type="text" class="form-control" value="{{$testimony->name}}" name="name"
                            placeholder="Product Name" />
                        <br>

                        <label for="product_image">Product Image</label><br>
                        <small class="text-muted">Current cover</small><br>
                        @if($testimony->image)
                        @php
                            $image = explode(',', $testimony->image);   
                            // var_dump($image);
                        @endphp
                        @foreach ($image as $item)
                            <img src="{{asset('uploads/testimony_images/' . $item)}}" width="96px" />
                        @endforeach
                        @endif
                        <br><br>
                        <input type="file" class="form-control" name="image[]" multiple>
                        <small class="text-muted">Kosongkan jika tidak ingin mengubah cover</small>
                        <br><br>

                        <label for="product_description">Testimony</label> <br>
                        <textarea name="testimony" id="product_description"
                            class="form-control">{{$testimony->testimony}}</textarea>
                        <br>
    
                        <select class="form-control"  name="is_publish">
                            <option value="0">Publish Later</option>
                            <option value="1">Publish Immadiately</option>
                        </select>
                        <br>

                        <button class="btn btn-primary" value="submit">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/testimonies/index.blade.php
@extends('admin.master')
@section('content')

<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Data testimonies</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="#">Dashboard</a></li>
                    <li class="breadcrumb-item">testimonies</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->

<!-- Page Content -->
<div class="content">
    @if(session('status'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{session('status')}}</p>
        </div>
    </div>
    @endif
    <!-- Dynamic Table Full -->
    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Dynamic Table <small>Full</small></h3>
            <div class="d-flex">
                <div class="input-group">
                    <div class="input-group-btn">
                        <a href="{{route('testimonies.create')}}" class="btn btn-success"><i
                                class="fas fa-plus-circle"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="block-content block-content-full">

            <!-- DataTables init on table by adding .js-dataTable-full class, functionality is initialized in js/pages/be_tables_datatables.min.js which was auto compiled from _es6/pages/be_tables_datatables.js -->
            <div style="overflow-x: scroll">
                
            <table class="table table-bordered table-striped table-vcenter">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 80px;">#</th>
                        <th><b>Name</b></th>
                        <th><b>Testimony</b></th>
                        <th><b>image</b></th>
                        <th><b>Publish</b></th>
                        <th><b>Action</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(testimony , i) in testimonies" :key="i">
                        <td class="text-center">@{{ testimony.id }}</td>
                        <td class="d-none d-sm-table-cell">@{{ testimony.name }}</td>
                        <td class="d-none d-sm-table-cell">@{{ testimony.testimony }}</td>
                                    <td class="d-none d-sm-table-cell">
                                        <img v-if="testimony.image" width="80"
                                            :src="uri + 'uploads/testimony_images/'+ convert(testimony.image)" alt="">
                                        <div v-else>Not set</div>
                                    </td>
                        <td class="d-none d-sm-table-cell" v-if="testimony.is_publish"><div class="badge badge-success">Published</div></td>
                        <td class="d-none d-sm-table-cell" v-else><div class="badge badge-dark">Not Published</div></td>

                        <td class="d-none d-sm-table-cell">
                            <a class="btn btn-info text-white btn-sm"
                                :href="uri + 'admin/testimonies/' + testimony.id + '/edit'">Edit</a>
                            <a href="#" @click="testimony_delete(testimony.id)" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
    </div>
    <!-- END Dynamic Table Full -->
</div>

@endsection

@section('script')

<script>
    var App = new Vue({
        el : '#app',
        data(){
            return{
                uri : 'http://127.0.0.1:8000/',
                testimonies : {},
                search : null,
            }
        },
        mounted() {
            this.testimonies_all();
        },
        methods : {
            testimonies_all(){
                axios.get(this.uri + 'api/testimonies/all').then(response => {
                    this.testimonies = response.data
                    console.log(response.data)
                }).catch(error => {
                    alert(error.response.data.message)
                })
            },
            convert(img){
                var image = img.split(',')
                console.log(image)
                return image[0] 
            },
            testimony_delete(id){
                Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        axios.delete(this.uri + 'api/testimonies/delete/' + id).then(response => {
                            this.testimonies_all();
                            Swal.fire(
                                'Good job!',
                                'You clicked the button!',
                                'success'
                            )
                        }).catch(error => console.log(error))
                        
                    }
                })
            }
        }
    })
</script>

@endsection